# Generated by Django 5.1.6 on 2025-04-26 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('plaid', 'Plaid')], default='manual', max_length=10),
        ),
        migrations.CreateModel(
            name='PlaidItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=255, unique=True)),
                ('access_token', models.CharField(max_length=255)),
                ('institution_id', models.CharField(max_length=100)),
                ('institution_name', models.CharField(max_length=255)),
                ('status', models.CharField(default='good', max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plaid_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaidAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('official_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mask', models.CharField(blank=True, max_length=4, null=True)),
                ('type', models.CharField(choices=[('depository', 'Depository'), ('credit', 'Credit'), ('loan', 'Loan'), ('investment', 'Investment'), ('other', 'Other')], max_length=50)),
                ('subtype', models.CharField(blank=True, max_length=50, null=True)),
                ('balance_available', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('balance_current', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('balance_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('plaid_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='api.plaiditem')),
            ],
            options={
                'unique_together': {('plaid_item', 'account_id')},
            },
        ),
        migrations.CreateModel(
            name='PlaidTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('merchant_name', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_channel', models.CharField(max_length=50)),
                ('pending', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('category_id', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.JSONField(blank=True, null=True)),
                ('payment_meta', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.plaidaccount')),
                ('expense', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plaid_transaction', to='api.expense')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
