# Generated by Django 5.1.6 on 2025-04-26 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
